### Request ###

PUT /auth/app-access/ HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "isActive": false
}

### Response ###

## HTTP CODE - 200 ##



## HTTP CODE - 400 ##



## HTTP CODE - 404 ##

