### Request ###

GET /auth/application/first-app HTTP/1.1
Host: localhost:3000
Content-Type: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 192
ETag: W/"c0-+rXkxkcK6eM9FBiNgG+EmuoUxUY"
Date: Fri, 02 Aug 2024 21:04:55 GMT
Connection: close

{
  "id": "89b4df19-bd80-498b-bb95-186efb85829e",
  "appSlug": "first-app",
  "appIp": "::ffff:127.0.0.1",
  "isActive": false,
  "createdAt": "2024-08-02T20:55:31.505Z",
  "updatedAt": "2024-08-02T20:55:31.505Z"
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 146
ETag: W/"92-Sa7rtmy7q2gaCNry47Ck2DfPIc8"
Date: Sat, 03 Aug 2024 15:46:13 GMT
Connection: close

{
  "statusCode": 404,
  "timestamp": "2024-08-03T15:46:13.626Z",
  "path": "/auth/application/first-app",
  "message": "Application with ID first-app not found"
}