### Request ###

GET /yahoo-finance/options?symbol=AAPL HTTP/1.1
Host: localhost:3000

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 47284
ETag: W/"b8b4-6JW39CfH/EOJWsojxpdq7Dx1SmU"
Date: Tue, 13 Aug 2024 22:33:37 GMT
Connection: close

{
  "underlyingSymbol": "AAPL",
  "expirationDates": [
    "2024-08-16T00:00:00.000Z",
    "2024-08-23T00:00:00.000Z",
    "2024-08-30T00:00:00.000Z",
    "2024-09-06T00:00:00.000Z",
    "2024-09-13T00:00:00.000Z",
    "2024-09-20T00:00:00.000Z",
    "2024-09-27T00:00:00.000Z",
    "2024-10-18T00:00:00.000Z",
    "2024-11-15T00:00:00.000Z",
    "2024-12-20T00:00:00.000Z",
    "2025-01-17T00:00:00.000Z",
    "2025-03-21T00:00:00.000Z",
    "2025-06-20T00:00:00.000Z",
    "2025-08-15T00:00:00.000Z",
    "2025-09-19T00:00:00.000Z",
    "2025-12-19T00:00:00.000Z",
    "2026-01-16T00:00:00.000Z",
    "2026-06-18T00:00:00.000Z",
    "2026-12-18T00:00:00.000Z"
  ],
  "strikes": [
    5,
    15,
    20,
    25,
    45,
    50,
    80,
    85,
    90,
    95,
    100,
    105,
    110,
    115,
    120,
    125,
    130,
    135,
    140,
    145,
    150,
    155,
    160,
    165,
    170,
    175,
    180,
    185,
    187.5,
    190,
    192.5,
    195,
    197.5,
    200,
    202.5,
    205,
    207.5,
    210,
    212.5,
    215,
    217.5,
    220,
    222.5,
    225,
    227.5,
    230,
    232.5,
    235,
    237.5,
    240,
    242.5,
    245,
    250,
    255,
    260,
    265,
    270,
    275,
    280,
    285,
    290,
    295,
    300,
    305,
    310,
    315,
    320,
    330,
    340,
    350,
    360,
    370
  ],
  "hasMiniOptions": false,
  "quote": {
    "language": "en-US",
    "region": "US",
    "quoteType": "EQUITY",
    "typeDisp": "Equity",
    "quoteSourceName": "Nasdaq Real Time Price",
    "triggerable": true,
    "customPriceAlertConfidence": "HIGH",
    "currency": "USD",
    "exchange": "NMS",
    "shortName": "Apple Inc.",
    "longName": "Apple Inc.",
    "messageBoardId": "finmb_24937",
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "market": "us_market",
    "esgPopulated": false,
    "regularMarketChangePercent": 1.7193056,
    "marketState": "POST",
    "regularMarketPrice": 221.27,
    "postMarketChangePercent": -0.28698412,
    "postMarketTime": "2024-08-13T22:33:15.000Z",
    "postMarketPrice": 220.635,
    "postMarketChange": -0.63500977,
    "regularMarketChange": 3.7400055,
    "regularMarketTime": "2024-08-13T20:00:01.000Z",
    "regularMarketDayHigh": 221.89,
    "regularMarketDayRange": {
      "low": 219.01,
      "high": 221.89
    },
    "regularMarketDayLow": 219.01,
    "regularMarketVolume": 41453325,
    "regularMarketPreviousClose": 217.53,
    "bid": 221.04,
    "ask": 221.18,
    "bidSize": 1,
    "askSize": 1,
    "fullExchangeName": "NasdaqGS",
    "financialCurrency": "USD",
    "regularMarketOpen": 219.105,
    "averageDailyVolume3Month": 65826293,
    "averageDailyVolume10Day": 63983030,
    "fiftyTwoWeekLowChange": 57.190002,
    "fiftyTwoWeekLowChangePercent": 0.3485495,
    "fiftyTwoWeekRange": {
      "low": 164.08,
      "high": 237.23
    },
    "fiftyTwoWeekHighChange": -15.959991,
    "fiftyTwoWeekHighChangePercent": -0.06727645,
    "fiftyTwoWeekLow": 164.08,
    "fiftyTwoWeekHigh": 237.23,
    "fiftyTwoWeekChangePercent": 22.586643,
    "dividendDate": "2024-08-15T00:00:00.000Z",
    "earningsTimestamp": "2024-08-01T20:30:00.000Z",
    "earningsTimestampStart": "2024-10-31T10:59:00.000Z",
    "earningsTimestampEnd": "2024-11-04T12:00:00.000Z",
    "earningsCallTimestampStart": 1722546000,
    "earningsCallTimestampEnd": 1722546000,
    "isEarningsDateEstimate": true,
    "trailingAnnualDividendRate": 0.97,
    "trailingPE": 33.678844,
    "dividendRate": 1,
    "trailingAnnualDividendYield": 0.0044591553,
    "dividendYield": 0.46,
    "epsTrailingTwelveMonths": 6.57,
    "epsForward": 6.85,
    "epsCurrentYear": 6.13,
    "priceEpsCurrentYear": 36.09625,
    "sharesOutstanding": 15204100096,
    "bookValue": 4.382,
    "fiftyDayAverage": 215.2808,
    "fiftyDayAverageChange": 5.989197,
    "fiftyDayAverageChangePercent": 0.027820393,
    "twoHundredDayAverage": 190.6497,
    "twoHundredDayAverageChange": 30.6203,
    "twoHundredDayAverageChangePercent": 0.16061027,
    "marketCap": 3364211392512,
    "forwardPE": 32.302193,
    "priceToBook": 50.49521,
    "sourceInterval": 15,
    "exchangeDataDelayedBy": 0,
    "averageAnalystRating": "2.0 - Buy",
    "tradeable": false,
    "cryptoTradeable": false,
    "hasPrePostMarketData": true,
    "firstTradeDateMilliseconds": "1980-12-12T14:30:00.000Z",
    "priceHint": 2,
    "displayName": "Apple",
    "symbol": "AAPL"
  },
  "options": [
    {
      "expirationDate": "2024-08-16T00:00:00.000Z",
      "hasMiniOptions": false,
      "calls": [
        {
          "contractSymbol": "AAPL240816C00005000",
          "strike": 5,
          "currency": "USD",
          "lastPrice": 206.54,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 0,
          "bid": 215.3,
          "ask": 216.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T17:41:05.000Z",
          "impliedVolatility": 18.53125420898438,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00015000",
          "strike": 15,
          "currency": "USD",
          "lastPrice": 218.3,
          "change": 0,
          "percentChange": 0,
          "volume": 6,
          "openInterest": 0,
          "bid": 205.3,
          "ask": 206.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-16T16:16:43.000Z",
          "impliedVolatility": 12.35156478027344,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00050000",
          "strike": 50,
          "currency": "USD",
          "lastPrice": 164.65,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 15,
          "bid": 179.7,
          "ask": 181.9,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-06-13T19:47:00.000Z",
          "impliedVolatility": 13.492189067382812,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00080000",
          "strike": 80,
          "currency": "USD",
          "lastPrice": 147.3,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 84,
          "bid": 134.95,
          "ask": 137.45,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-11T15:06:40.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00085000",
          "strike": 85,
          "currency": "USD",
          "lastPrice": 130.38,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 0,
          "bid": 135.4,
          "ask": 136.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:42:39.000Z",
          "impliedVolatility": 4.4804731494140615,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00090000",
          "strike": 90,
          "currency": "USD",
          "lastPrice": 125.39,
          "change": 0,
          "percentChange": 0,
          "volume": 20,
          "openInterest": 0,
          "bid": 130.4,
          "ask": 132.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:42:39.000Z",
          "impliedVolatility": 4.582035522460938,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00095000",
          "strike": 95,
          "currency": "USD",
          "lastPrice": 120.41,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 2,
          "bid": 125.4,
          "ask": 126.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:42:39.000Z",
          "impliedVolatility": 3.9980468798828124,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00100000",
          "strike": 100,
          "currency": "USD",
          "lastPrice": 110.44,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 14,
          "bid": 120.4,
          "ask": 122.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-07T19:29:03.000Z",
          "impliedVolatility": 4.091801760253906,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00105000",
          "strike": 105,
          "currency": "USD",
          "lastPrice": 109.14,
          "change": 0,
          "percentChange": 0,
          "volume": 7,
          "openInterest": 0,
          "bid": 115.4,
          "ask": 116.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T14:35:23.000Z",
          "impliedVolatility": 3.5644542138671875,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00110000",
          "strike": 110,
          "currency": "USD",
          "lastPrice": 105.5,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 8,
          "bid": 110.45,
          "ask": 112.1,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T15:05:11.000Z",
          "impliedVolatility": 2.0625048437499998,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00115000",
          "strike": 115,
          "currency": "USD",
          "lastPrice": 89.75,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 28,
          "bid": 105.35,
          "ask": 106.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-06T14:07:24.000Z",
          "impliedVolatility": 3.1718770703125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00120000",
          "strike": 120,
          "currency": "USD",
          "lastPrice": 93.34,
          "change": 0,
          "percentChange": 0,
          "volume": 7,
          "openInterest": 46,
          "bid": 100.45,
          "ask": 101.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-08T17:10:01.000Z",
          "impliedVolatility": 2.9863306591796874,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00125000",
          "strike": 125,
          "currency": "USD",
          "lastPrice": 92.32,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 22,
          "bid": 95.4,
          "ask": 96.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T19:30:34.000Z",
          "impliedVolatility": 2.8085967285156253,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00130000",
          "strike": 130,
          "currency": "USD",
          "lastPrice": 83.2,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 7,
          "bid": 90.45,
          "ask": 92.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T13:37:01.000Z",
          "impliedVolatility": 1.8515632421875,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00135000",
          "strike": 135,
          "currency": "USD",
          "lastPrice": 82.15,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1,
          "bid": 85.4,
          "ask": 86.8,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T13:32:21.000Z",
          "impliedVolatility": 2.513675590820312,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00140000",
          "strike": 140,
          "currency": "USD",
          "lastPrice": 79.44,
          "change": 4.1800003,
          "percentChange": 5.5540795,
          "volume": 1,
          "openInterest": 64,
          "bid": 80.5,
          "ask": 82.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T13:30:01.000Z",
          "impliedVolatility": 1.71875140625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00145000",
          "strike": 145,
          "currency": "USD",
          "lastPrice": 72.39,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 24,
          "bid": 75.4,
          "ask": 77.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T19:27:53.000Z",
          "impliedVolatility": 1.2500037499999999,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00150000",
          "strike": 150,
          "currency": "USD",
          "lastPrice": 70.65,
          "change": 3.340004,
          "percentChange": 4.9621215,
          "volume": 2,
          "openInterest": 45,
          "bid": 70.45,
          "ask": 72.1,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T15:58:23.000Z",
          "impliedVolatility": 1.1875040625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00155000",
          "strike": 155,
          "currency": "USD",
          "lastPrice": 66.5,
          "change": 5.549999,
          "percentChange": 9.1058235,
          "volume": 5,
          "openInterest": 7,
          "bid": 65.5,
          "ask": 67.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T15:54:13.000Z",
          "impliedVolatility": 1.09375453125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00160000",
          "strike": 160,
          "currency": "USD",
          "lastPrice": 61.1,
          "change": 4.919998,
          "percentChange": 8.757562,
          "volume": 2,
          "openInterest": 34,
          "bid": 60.5,
          "ask": 61.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T14:59:55.000Z",
          "impliedVolatility": 1.685548447265625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00165000",
          "strike": 165,
          "currency": "USD",
          "lastPrice": 56.03,
          "change": 5.1399994,
          "percentChange": 10.100215,
          "volume": 2,
          "openInterest": 18,
          "bid": 55.45,
          "ask": 57.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:50:39.000Z",
          "impliedVolatility": 1.7373060009765624,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00170000",
          "strike": 170,
          "currency": "USD",
          "lastPrice": 50.77,
          "change": 3.7700005,
          "percentChange": 8.021277,
          "volume": 9,
          "openInterest": 193,
          "bid": 50.7,
          "ask": 52.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:20:47.000Z",
          "impliedVolatility": 1.1953165234375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00175000",
          "strike": 175,
          "currency": "USD",
          "lastPrice": 46,
          "change": 3.9199982,
          "percentChange": 9.315584,
          "volume": 24,
          "openInterest": 1190,
          "bid": 45.35,
          "ask": 47.1,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T16:05:13.000Z",
          "impliedVolatility": 1.466799541015625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00180000",
          "strike": 180,
          "currency": "USD",
          "lastPrice": 41,
          "change": 3.5299988,
          "percentChange": 9.420866,
          "volume": 76,
          "openInterest": 3114,
          "bid": 41.1,
          "ask": 41.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:45:09.000Z",
          "impliedVolatility": 0.9414068359375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00185000",
          "strike": 185,
          "currency": "USD",
          "lastPrice": 36.2,
          "change": 3.8199997,
          "percentChange": 11.797404,
          "volume": 74,
          "openInterest": 9278,
          "bid": 36.1,
          "ask": 36.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:47:30.000Z",
          "impliedVolatility": 0.8339860351562498,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00187500",
          "strike": 187.5,
          "currency": "USD",
          "lastPrice": 30.21,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 23,
          "bid": 33,
          "ask": 34.65,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T15:36:18.000Z",
          "impliedVolatility": 0.6894562304687502,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00190000",
          "strike": 190,
          "currency": "USD",
          "lastPrice": 31.15,
          "change": 3.6499996,
          "percentChange": 13.272726,
          "volume": 142,
          "openInterest": 21357,
          "bid": 31.1,
          "ask": 31.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:21.000Z",
          "impliedVolatility": 0.7246121289062499,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00195000",
          "strike": 195,
          "currency": "USD",
          "lastPrice": 26.13,
          "change": 4.129999,
          "percentChange": 18.772722,
          "volume": 520,
          "openInterest": 25957,
          "bid": 26.1,
          "ask": 26.8,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:57:25.000Z",
          "impliedVolatility": 0.6533237792968751,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00197500",
          "strike": 197.5,
          "currency": "USD",
          "lastPrice": 23.05,
          "change": 1.2799988,
          "percentChange": 5.8796453,
          "volume": 4,
          "openInterest": 485,
          "bid": 23.15,
          "ask": 24.5,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T13:47:15.000Z",
          "impliedVolatility": 0.8071308349609375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00200000",
          "strike": 200,
          "currency": "USD",
          "lastPrice": 21.05,
          "change": 3.6899986,
          "percentChange": 21.255753,
          "volume": 1049,
          "openInterest": 14644,
          "bid": 21.15,
          "ask": 21.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:53:00.000Z",
          "impliedVolatility": 0.5429733203125001,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00202500",
          "strike": 202.5,
          "currency": "USD",
          "lastPrice": 18.43,
          "change": 3.63,
          "percentChange": 24.527027,
          "volume": 46,
          "openInterest": 1456,
          "bid": 18.5,
          "ask": 19.45,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:31:56.000Z",
          "impliedVolatility": 0.657229990234375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00205000",
          "strike": 205,
          "currency": "USD",
          "lastPrice": 16.5,
          "change": 3.6000004,
          "percentChange": 27.90698,
          "volume": 629,
          "openInterest": 12182,
          "bid": 16.2,
          "ask": 16.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:23.000Z",
          "impliedVolatility": 0.5639692041015626,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00207500",
          "strike": 207.5,
          "currency": "USD",
          "lastPrice": 13.35,
          "change": 3.1100006,
          "percentChange": 30.3711,
          "volume": 255,
          "openInterest": 2251,
          "bid": 13.7,
          "ask": 14.25,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:40:18.000Z",
          "impliedVolatility": 0.471684970703125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00210000",
          "strike": 210,
          "currency": "USD",
          "lastPrice": 11.64,
          "change": 3.2700005,
          "percentChange": 39.068108,
          "volume": 3399,
          "openInterest": 30642,
          "bid": 11.35,
          "ask": 11.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:33.000Z",
          "impliedVolatility": 0.4279842358398438,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00212500",
          "strike": 212.5,
          "currency": "USD",
          "lastPrice": 9.16,
          "change": 2.87,
          "percentChange": 45.627983,
          "volume": 1061,
          "openInterest": 3688,
          "bid": 9,
          "ask": 9.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:32.000Z",
          "impliedVolatility": 0.3676821044921875,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00215000",
          "strike": 215,
          "currency": "USD",
          "lastPrice": 6.85,
          "change": 2.4499998,
          "percentChange": 55.681812,
          "volume": 3158,
          "openInterest": 35377,
          "bid": 6.9,
          "ask": 7.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:55.000Z",
          "impliedVolatility": 0.3181220532226562,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00217500",
          "strike": 217.5,
          "currency": "USD",
          "lastPrice": 4.71,
          "change": 1.9100001,
          "percentChange": 68.214294,
          "volume": 6868,
          "openInterest": 10220,
          "bid": 4.75,
          "ask": 4.9,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:57.000Z",
          "impliedVolatility": 0.2827220166015625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00220000",
          "strike": 220,
          "currency": "USD",
          "lastPrice": 3,
          "change": 1.4,
          "percentChange": 87.5,
          "volume": 33668,
          "openInterest": 40926,
          "bid": 3,
          "ask": 3.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:59.000Z",
          "impliedVolatility": 0.2561109545898438,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00222500",
          "strike": 222.5,
          "currency": "USD",
          "lastPrice": 1.65,
          "change": 0.89,
          "percentChange": 117.10526,
          "volume": 39250,
          "openInterest": 9235,
          "bid": 1.62,
          "ask": 1.66,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:58.000Z",
          "impliedVolatility": 0.23975369628906246,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00225000",
          "strike": 225,
          "currency": "USD",
          "lastPrice": 0.76,
          "change": 0.44,
          "percentChange": 137.5,
          "volume": 43168,
          "openInterest": 47814,
          "bid": 0.74,
          "ask": 0.78,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:58.000Z",
          "impliedVolatility": 0.23072058349609376,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00227500",
          "strike": 227.5,
          "currency": "USD",
          "lastPrice": 0.31,
          "change": 0.19,
          "percentChange": 158.33333,
          "volume": 16447,
          "openInterest": 8531,
          "bid": 0.31,
          "ask": 0.32,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:55.000Z",
          "impliedVolatility": 0.22705851074218747,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00230000",
          "strike": 230,
          "currency": "USD",
          "lastPrice": 0.13,
          "change": 0.089999996,
          "percentChange": 225,
          "volume": 47178,
          "openInterest": 70464,
          "bid": 0.12,
          "ask": 0.13,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:57.000Z",
          "impliedVolatility": 0.23242955078125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00232500",
          "strike": 232.5,
          "currency": "USD",
          "lastPrice": 0.05,
          "change": 0.030000001,
          "percentChange": 150,
          "volume": 4022,
          "openInterest": 3837,
          "bid": 0.05,
          "ask": 0.06,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:17.000Z",
          "impliedVolatility": 0.245124736328125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00235000",
          "strike": 235,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": 0.01,
          "percentChange": 50,
          "volume": 9509,
          "openInterest": 29986,
          "bid": 0.02,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:16.000Z",
          "impliedVolatility": 0.2617261328125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00237500",
          "strike": 237.5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 275,
          "openInterest": 2201,
          "bid": 0.01,
          "ask": 0.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:39:03.000Z",
          "impliedVolatility": 0.28516339843749994,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00240000",
          "strike": 240,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 2779,
          "openInterest": 31825,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:43:24.000Z",
          "impliedVolatility": 0.29688203124999996,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00242500",
          "strike": 242.5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 365,
          "openInterest": 951,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T18:56:55.000Z",
          "impliedVolatility": 0.32813171874999997,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00245000",
          "strike": 245,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 132,
          "openInterest": 18120,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:04:24.000Z",
          "impliedVolatility": 0.35938140625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00250000",
          "strike": 250,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 161,
          "openInterest": 45045,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:52:00.000Z",
          "impliedVolatility": 0.42969320312500003,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00255000",
          "strike": 255,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 108,
          "openInterest": 7142,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:02:56.000Z",
          "impliedVolatility": 0.48438015625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00260000",
          "strike": 260,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 45,
          "openInterest": 12990,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:42:00.000Z",
          "impliedVolatility": 0.51562984375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00265000",
          "strike": 265,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 9,
          "openInterest": 1843,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:01:19.000Z",
          "impliedVolatility": 0.5625043750000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00270000",
          "strike": 270,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 25,
          "openInterest": 3531,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:42:00.000Z",
          "impliedVolatility": 0.6250037500000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00275000",
          "strike": 275,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 3294,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T14:27:46.000Z",
          "impliedVolatility": 0.6718782812500002,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00280000",
          "strike": 280,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 25,
          "openInterest": 1956,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:42:00.000Z",
          "impliedVolatility": 0.7187528125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00285000",
          "strike": 285,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 645,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T18:34:24.000Z",
          "impliedVolatility": 0.7812521875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00290000",
          "strike": 290,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 20,
          "openInterest": 2862,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:42:00.000Z",
          "impliedVolatility": 0.8125018749999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00295000",
          "strike": 295,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 271,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T16:41:45.000Z",
          "impliedVolatility": 0.87500125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00300000",
          "strike": 300,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 4230,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:48:58.000Z",
          "impliedVolatility": 0.9062509375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00305000",
          "strike": 305,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 152,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:49:02.000Z",
          "impliedVolatility": 0.9687503125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00310000",
          "strike": 310,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 363,
          "openInterest": 1568,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-02T19:40:41.000Z",
          "impliedVolatility": 1.000005,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00315000",
          "strike": 315,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 578,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:49:05.000Z",
          "impliedVolatility": 1.0625046875000002,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00320000",
          "strike": 320,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 2343,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T16:23:25.000Z",
          "impliedVolatility": 1.09375453125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00330000",
          "strike": 330,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1534,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T13:30:09.000Z",
          "impliedVolatility": 1.1875040625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00340000",
          "strike": 340,
          "currency": "USD",
          "lastPrice": 0.06,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 3953,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-02T17:02:29.000Z",
          "impliedVolatility": 1.2500037499999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00350000",
          "strike": 350,
          "currency": "USD",
          "lastPrice": 0.2,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 1194,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T17:18:17.000Z",
          "impliedVolatility": 1.3125034374999998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00360000",
          "strike": 360,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1326,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T13:30:01.000Z",
          "impliedVolatility": 1.40625296875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00370000",
          "strike": 370,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 251,
          "openInterest": 5672,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T13:39:30.000Z",
          "impliedVolatility": 1.46875265625,
          "inTheMoney": false
        }
      ],
      "puts": [
        {
          "contractSymbol": "AAPL240816P00005000",
          "strike": 5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 4,
          "openInterest": 5,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T13:30:05.000Z",
          "impliedVolatility": 11.000003125000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00015000",
          "strike": 15,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "openInterest": 126,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T14:33:15.000Z",
          "impliedVolatility": 8.125004921875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00020000",
          "strike": 20,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-03-22T13:38:52.000Z",
          "impliedVolatility": 6.87500140625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00025000",
          "strike": 25,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 3,
          "openInterest": 4,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-05-14T19:13:50.000Z",
          "impliedVolatility": 6.2500021875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00045000",
          "strike": 45,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 40,
          "openInterest": 40,
          "bid": 0,
          "ask": 0.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-03-14T13:30:04.000Z",
          "impliedVolatility": 5.187503515625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00050000",
          "strike": 50,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 250,
          "openInterest": 188,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T19:39:20.000Z",
          "impliedVolatility": 4.2500046875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00080000",
          "strike": 80,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 309,
          "openInterest": 620,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T14:16:22.000Z",
          "impliedVolatility": 2.93750265625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00085000",
          "strike": 85,
          "currency": "USD",
          "lastPrice": 0.02,
          "change": 0,
          "percentChange": 0,
          "volume": 3,
          "openInterest": 721,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T19:12:03.000Z",
          "impliedVolatility": 2.750003125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00090000",
          "strike": 90,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": 0,
          "percentChange": 0,
          "volume": 82,
          "openInterest": 547,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T14:14:14.000Z",
          "impliedVolatility": 2.6250034375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00095000",
          "strike": 95,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 4,
          "openInterest": 1358,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-07T13:30:07.000Z",
          "impliedVolatility": 2.43750390625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00100000",
          "strike": 100,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 2495,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T13:34:42.000Z",
          "impliedVolatility": 2.3125042187499996,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00105000",
          "strike": 105,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 5845,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-08T16:22:07.000Z",
          "impliedVolatility": 2.1875045312499997,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00110000",
          "strike": 110,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 3050,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:17:52.000Z",
          "impliedVolatility": 2.0625048437499998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00115000",
          "strike": 115,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 330,
          "openInterest": 4006,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T14:01:20.000Z",
          "impliedVolatility": 1.9375003125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00120000",
          "strike": 120,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 4,
          "openInterest": 2544,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T14:02:07.000Z",
          "impliedVolatility": 1.8125009374999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00125000",
          "strike": 125,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 3433,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:12:24.000Z",
          "impliedVolatility": 1.6875015625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00130000",
          "strike": 130,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 4229,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T13:31:12.000Z",
          "impliedVolatility": 1.5625021874999998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00135000",
          "strike": 135,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 3088,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T15:12:37.000Z",
          "impliedVolatility": 1.46875265625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00140000",
          "strike": 140,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 12,
          "openInterest": 7457,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T18:23:43.000Z",
          "impliedVolatility": 1.3750031249999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00145000",
          "strike": 145,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 41,
          "openInterest": 4333,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T14:37:36.000Z",
          "impliedVolatility": 1.2812535937499998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00150000",
          "strike": 150,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 9950,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T15:32:49.000Z",
          "impliedVolatility": 1.1875040625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00155000",
          "strike": 155,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 11,
          "openInterest": 5715,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T14:52:38.000Z",
          "impliedVolatility": 1.09375453125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00160000",
          "strike": 160,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1471,
          "openInterest": 7233,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:53:04.000Z",
          "impliedVolatility": 0.98437515625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00165000",
          "strike": 165,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 6,
          "openInterest": 12526,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T16:35:53.000Z",
          "impliedVolatility": 0.9062509375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00170000",
          "strike": 170,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 924,
          "openInterest": 14170,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:54:34.000Z",
          "impliedVolatility": 0.8125018749999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00175000",
          "strike": 175,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1015,
          "openInterest": 11203,
          "bid": 0,
          "ask": 0.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:43:11.000Z",
          "impliedVolatility": 0.7812521875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00180000",
          "strike": 180,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": -0.01,
          "percentChange": -50,
          "volume": 380,
          "openInterest": 47187,
          "bid": 0.01,
          "ask": 0.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:46.000Z",
          "impliedVolatility": 0.726565234375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00185000",
          "strike": 185,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": -0.01,
          "percentChange": -25,
          "volume": 783,
          "openInterest": 28200,
          "bid": 0.01,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:57:58.000Z",
          "impliedVolatility": 0.6562534375000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00187500",
          "strike": 187.5,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": -0.020000001,
          "percentChange": -40.000004,
          "volume": 1199,
          "openInterest": 3445,
          "bid": 0.02,
          "ask": 0.04,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:37:27.000Z",
          "impliedVolatility": 0.64062859375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00190000",
          "strike": 190,
          "currency": "USD",
          "lastPrice": 0.04,
          "change": -0.010000002,
          "percentChange": -20.000002,
          "volume": 9716,
          "openInterest": 50572,
          "bid": 0.03,
          "ask": 0.04,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:14.000Z",
          "impliedVolatility": 0.6054726953125001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00192500",
          "strike": 192.5,
          "currency": "USD",
          "lastPrice": 0.04,
          "change": -0.030000001,
          "percentChange": -42.857143,
          "volume": 322,
          "openInterest": 1568,
          "bid": 0.03,
          "ask": 0.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:37:42.000Z",
          "impliedVolatility": 0.570316796875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00195000",
          "strike": 195,
          "currency": "USD",
          "lastPrice": 0.05,
          "change": -0.040000003,
          "percentChange": -44.444447,
          "volume": 941,
          "openInterest": 26432,
          "bid": 0.04,
          "ask": 0.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:48.000Z",
          "impliedVolatility": 0.5312546875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00197500",
          "strike": 197.5,
          "currency": "USD",
          "lastPrice": 0.06,
          "change": -0.05,
          "percentChange": -45.454544,
          "volume": 889,
          "openInterest": 5194,
          "bid": 0.06,
          "ask": 0.07,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:56:33.000Z",
          "impliedVolatility": 0.507817421875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00200000",
          "strike": 200,
          "currency": "USD",
          "lastPrice": 0.07,
          "change": -0.07,
          "percentChange": -50,
          "volume": 8102,
          "openInterest": 36330,
          "bid": 0.07,
          "ask": 0.08,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:53.000Z",
          "impliedVolatility": 0.47461462890625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00202500",
          "strike": 202.5,
          "currency": "USD",
          "lastPrice": 0.09,
          "change": -0.11,
          "percentChange": -55,
          "volume": 2386,
          "openInterest": 10702,
          "bid": 0.08,
          "ask": 0.1,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:54:19.000Z",
          "impliedVolatility": 0.43945873046875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00205000",
          "strike": 205,
          "currency": "USD",
          "lastPrice": 0.11,
          "change": -0.17999999,
          "percentChange": -62.068966,
          "volume": 6504,
          "openInterest": 31385,
          "bid": 0.11,
          "ask": 0.12,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:39.000Z",
          "impliedVolatility": 0.40039662109375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00207500",
          "strike": 207.5,
          "currency": "USD",
          "lastPrice": 0.15,
          "change": -0.28,
          "percentChange": -65.11628,
          "volume": 7403,
          "openInterest": 9103,
          "bid": 0.14,
          "ask": 0.16,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:58:43.000Z",
          "impliedVolatility": 0.366217275390625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00210000",
          "strike": 210,
          "currency": "USD",
          "lastPrice": 0.21,
          "change": -0.42000002,
          "percentChange": -66.666664,
          "volume": 18606,
          "openInterest": 44541,
          "bid": 0.21,
          "ask": 0.22,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:48.000Z",
          "impliedVolatility": 0.33301448242187504,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00212500",
          "strike": 212.5,
          "currency": "USD",
          "lastPrice": 0.33,
          "change": -0.7199999,
          "percentChange": -68.57143,
          "volume": 33483,
          "openInterest": 7692,
          "bid": 0.31,
          "ask": 0.34,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:47.000Z",
          "impliedVolatility": 0.305671005859375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00215000",
          "strike": 215,
          "currency": "USD",
          "lastPrice": 0.53,
          "change": -1.13,
          "percentChange": -68.07229,
          "volume": 28954,
          "openInterest": 24738,
          "bid": 0.51,
          "ask": 0.55,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:52.000Z",
          "impliedVolatility": 0.2795482202148437,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00217500",
          "strike": 217.5,
          "currency": "USD",
          "lastPrice": 0.91,
          "change": -1.6699998,
          "percentChange": -64.728676,
          "volume": 23925,
          "openInterest": 7599,
          "bid": 0.89,
          "ask": 0.93,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:33.000Z",
          "impliedVolatility": 0.2563550927734375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00220000",
          "strike": 220,
          "currency": "USD",
          "lastPrice": 1.65,
          "change": -2.35,
          "percentChange": -58.749996,
          "volume": 45564,
          "openInterest": 13942,
          "bid": 1.57,
          "ask": 1.62,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:59.000Z",
          "impliedVolatility": 0.23853300537109373,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00222500",
          "strike": 222.5,
          "currency": "USD",
          "lastPrice": 2.79,
          "change": -3.1100001,
          "percentChange": -52.711864,
          "volume": 5754,
          "openInterest": 1026,
          "bid": 2.65,
          "ask": 2.79,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:52.000Z",
          "impliedVolatility": 0.22852333984375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00225000",
          "strike": 225,
          "currency": "USD",
          "lastPrice": 4.35,
          "change": -3.4100003,
          "percentChange": -43.943302,
          "volume": 6141,
          "openInterest": 10661,
          "bid": 4.35,
          "ask": 4.5,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:54.000Z",
          "impliedVolatility": 0.22925575439453127,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00227500",
          "strike": 227.5,
          "currency": "USD",
          "lastPrice": 6.49,
          "change": -3.5100002,
          "percentChange": -35.100002,
          "volume": 995,
          "openInterest": 524,
          "bid": 6.05,
          "ask": 6.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:40.000Z",
          "impliedVolatility": 0.2563550927734375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00230000",
          "strike": 230,
          "currency": "USD",
          "lastPrice": 9.59,
          "change": -3.3099995,
          "percentChange": -25.65891,
          "volume": 496,
          "openInterest": 3319,
          "bid": 8.55,
          "ask": 8.95,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:36:50.000Z",
          "impliedVolatility": 0.2617261328125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00232500",
          "strike": 232.5,
          "currency": "USD",
          "lastPrice": 11.41,
          "change": -4.45,
          "percentChange": -28.058006,
          "volume": 37,
          "openInterest": 12,
          "bid": 10.7,
          "ask": 11.95,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:52:01.000Z",
          "impliedVolatility": 0.4335994140625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00235000",
          "strike": 235,
          "currency": "USD",
          "lastPrice": 13.85,
          "change": -3.9499989,
          "percentChange": -22.191006,
          "volume": 1129,
          "openInterest": 2327,
          "bid": 13.4,
          "ask": 14.1,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:59:12.000Z",
          "impliedVolatility": 0.41358008300781246,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00237500",
          "strike": 237.5,
          "currency": "USD",
          "lastPrice": 20.46,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 2,
          "bid": 15.65,
          "ask": 17,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T19:29:59.000Z",
          "impliedVolatility": 0.5659223095703125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00240000",
          "strike": 240,
          "currency": "USD",
          "lastPrice": 19.25,
          "change": -3.75,
          "percentChange": -16.304348,
          "volume": 1219,
          "openInterest": 850,
          "bid": 18.4,
          "ask": 19.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T19:53:23.000Z",
          "impliedVolatility": 0.534184345703125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00242500",
          "strike": 242.5,
          "currency": "USD",
          "lastPrice": 29.93,
          "change": 0,
          "percentChange": 0,
          "openInterest": 4,
          "bid": 20.65,
          "ask": 21.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-07T16:41:49.000Z",
          "impliedVolatility": 0.6425816992187501,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00245000",
          "strike": 245,
          "currency": "USD",
          "lastPrice": 24,
          "change": -3.9099998,
          "percentChange": -14.0093155,
          "volume": 1,
          "openInterest": 0,
          "bid": 23.15,
          "ask": 24.5,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T18:06:26.000Z",
          "impliedVolatility": 0.7338893798828124,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00250000",
          "strike": 250,
          "currency": "USD",
          "lastPrice": 32,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 0,
          "bid": 28.2,
          "ask": 29.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T14:18:06.000Z",
          "impliedVolatility": 0.5371140039062501,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00255000",
          "strike": 255,
          "currency": "USD",
          "lastPrice": 39.95,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1,
          "bid": 33.35,
          "ask": 34.45,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T19:55:23.000Z",
          "impliedVolatility": 0.6972686523437501,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00260000",
          "strike": 260,
          "currency": "USD",
          "lastPrice": 50.75,
          "change": 0,
          "percentChange": 0,
          "volume": 55,
          "openInterest": 0,
          "bid": 38.3,
          "ask": 39.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T18:40:15.000Z",
          "impliedVolatility": 0.73437765625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00270000",
          "strike": 270,
          "currency": "USD",
          "lastPrice": 47.7,
          "change": 0,
          "percentChange": 0,
          "openInterest": 0,
          "bid": 48.35,
          "ask": 49.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-31T19:54:43.000Z",
          "impliedVolatility": 0.901368173828125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00275000",
          "strike": 275,
          "currency": "USD",
          "lastPrice": 41.03,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 0,
          "bid": 53.2,
          "ask": 54.45,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-15T19:46:03.000Z",
          "impliedVolatility": 0.9160164648437501,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00290000",
          "strike": 290,
          "currency": "USD",
          "lastPrice": 77,
          "change": 0,
          "percentChange": 0,
          "bid": 68.35,
          "ask": 69.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T15:23:48.000Z",
          "impliedVolatility": 1.1679729101562502,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00330000",
          "strike": 330,
          "currency": "USD",
          "lastPrice": 107.25,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 0,
          "bid": 108.3,
          "ask": 109.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-31T18:59:38.000Z",
          "impliedVolatility": 1.5878926855468747,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00340000",
          "strike": 340,
          "currency": "USD",
          "lastPrice": 119.45,
          "change": 0,
          "percentChange": 0,
          "openInterest": 0,
          "bid": 118.3,
          "ask": 119.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-01T15:35:09.000Z",
          "impliedVolatility": 1.6875015625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00370000",
          "strike": 370,
          "currency": "USD",
          "lastPrice": 159.85,
          "change": 0,
          "percentChange": 0,
          "openInterest": 0,
          "bid": 151.75,
          "ask": 153.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-06-25T18:14:36.000Z",
          "impliedVolatility": 3.4765638085937502,
          "inTheMoney": true
        }
      ]
    }
  ]
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Options data for symbol AAPL not found",
  "error": "Not Found"
}