### Request ###

GET /yahoo-finance/options?symbol=AAPL HTTP/1.1
Host: localhost:3010

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 24
X-RateLimit-Reset: 60
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 9
X-RateLimit-Reset-short: 60
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 69
X-RateLimit-Reset-longer: 60
Content-Type: application/json; charset=utf-8
Content-Length: 47307
ETag: W/"b8cb-/pxL4ZcSm5sIE0JToRTgXSyFr4c"
Date: Wed, 14 Aug 2024 18:48:21 GMT
Connection: close

{
  "underlyingSymbol": "AAPL",
  "expirationDates": [
    "2024-08-16T00:00:00.000Z",
    "2024-08-23T00:00:00.000Z",
    "2024-08-30T00:00:00.000Z",
    "2024-09-06T00:00:00.000Z",
    "2024-09-13T00:00:00.000Z",
    "2024-09-20T00:00:00.000Z",
    "2024-09-27T00:00:00.000Z",
    "2024-10-18T00:00:00.000Z",
    "2024-11-15T00:00:00.000Z",
    "2024-12-20T00:00:00.000Z",
    "2025-01-17T00:00:00.000Z",
    "2025-03-21T00:00:00.000Z",
    "2025-06-20T00:00:00.000Z",
    "2025-08-15T00:00:00.000Z",
    "2025-09-19T00:00:00.000Z",
    "2025-12-19T00:00:00.000Z",
    "2026-01-16T00:00:00.000Z",
    "2026-06-18T00:00:00.000Z",
    "2026-12-18T00:00:00.000Z"
  ],
  "strikes": [
    5,
    15,
    20,
    25,
    45,
    50,
    80,
    85,
    90,
    95,
    100,
    105,
    110,
    115,
    120,
    125,
    130,
    135,
    140,
    145,
    150,
    155,
    160,
    165,
    170,
    175,
    180,
    185,
    187.5,
    190,
    192.5,
    195,
    197.5,
    200,
    202.5,
    205,
    207.5,
    210,
    212.5,
    215,
    217.5,
    220,
    222.5,
    225,
    227.5,
    230,
    232.5,
    235,
    237.5,
    240,
    242.5,
    245,
    250,
    255,
    260,
    265,
    270,
    275,
    280,
    285,
    290,
    295,
    300,
    305,
    310,
    315,
    320,
    330,
    340,
    350,
    360,
    370
  ],
  "hasMiniOptions": false,
  "quote": {
    "language": "en-US",
    "region": "US",
    "quoteType": "EQUITY",
    "typeDisp": "Equity",
    "quoteSourceName": "Nasdaq Real Time Price",
    "triggerable": true,
    "customPriceAlertConfidence": "HIGH",
    "currency": "USD",
    "hasPrePostMarketData": true,
    "firstTradeDateMilliseconds": "1980-12-12T14:30:00.000Z",
    "priceHint": 2,
    "marketState": "REGULAR",
    "exchange": "NMS",
    "shortName": "Apple Inc.",
    "longName": "Apple Inc.",
    "messageBoardId": "finmb_24937",
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "market": "us_market",
    "esgPopulated": false,
    "regularMarketChangePercent": -0.10846725,
    "regularMarketPrice": 221.03,
    "regularMarketChange": -0.2400055,
    "regularMarketTime": "2024-08-14T18:48:19.000Z",
    "regularMarketDayHigh": 223.03,
    "regularMarketDayRange": {
      "low": 219.7,
      "high": 223.03
    },
    "regularMarketDayLow": 219.7,
    "regularMarketVolume": 26377020,
    "regularMarketPreviousClose": 221.27,
    "bid": 220.99,
    "ask": 221.05,
    "bidSize": 1,
    "askSize": 2,
    "fullExchangeName": "NasdaqGS",
    "financialCurrency": "USD",
    "regularMarketOpen": 220.565,
    "averageDailyVolume3Month": 65693027,
    "averageDailyVolume10Day": 64231760,
    "fiftyTwoWeekLowChange": 56.949997,
    "fiftyTwoWeekLowChangePercent": 0.34708676,
    "fiftyTwoWeekRange": {
      "low": 164.08,
      "high": 237.23
    },
    "fiftyTwoWeekHighChange": -16.199997,
    "fiftyTwoWeekHighChangePercent": -0.06828815,
    "fiftyTwoWeekLow": 164.08,
    "fiftyTwoWeekHigh": 237.23,
    "fiftyTwoWeekChangePercent": 25.315739,
    "dividendDate": "2024-08-15T00:00:00.000Z",
    "earningsTimestamp": "2024-08-01T20:30:00.000Z",
    "earningsTimestampStart": "2024-10-31T10:59:00.000Z",
    "earningsTimestampEnd": "2024-11-04T12:00:00.000Z",
    "earningsCallTimestampStart": 1722546000,
    "earningsCallTimestampEnd": 1722546000,
    "isEarningsDateEstimate": true,
    "trailingAnnualDividendRate": 0.97,
    "trailingPE": 33.64231,
    "dividendRate": 1,
    "trailingAnnualDividendYield": 0.0043837847,
    "dividendYield": 0.45,
    "epsTrailingTwelveMonths": 6.57,
    "epsForward": 7.48,
    "epsCurrentYear": 6.7,
    "priceEpsCurrentYear": 32.98955,
    "sharesOutstanding": 15204100096,
    "bookValue": 4.382,
    "fiftyDayAverage": 215.8612,
    "fiftyDayAverageChange": 5.1687927,
    "fiftyDayAverageChangePercent": 0.023944981,
    "twoHundredDayAverage": 190.90054,
    "twoHundredDayAverageChange": 30.129456,
    "twoHundredDayAverageChangePercent": 0.15782802,
    "marketCap": 3360562348032,
    "forwardPE": 29.549465,
    "priceToBook": 50.440437,
    "sourceInterval": 15,
    "exchangeDataDelayedBy": 0,
    "averageAnalystRating": "2.0 - Buy",
    "tradeable": false,
    "cryptoTradeable": false,
    "displayName": "Apple",
    "symbol": "AAPL"
  },
  "options": [
    {
      "expirationDate": "2024-08-16T00:00:00.000Z",
      "hasMiniOptions": false,
      "calls": [
        {
          "contractSymbol": "AAPL240816C00005000",
          "strike": 5,
          "currency": "USD",
          "lastPrice": 206.54,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 0,
          "bid": 215.6,
          "ask": 217.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T17:41:05.000Z",
          "impliedVolatility": 20.578128569335938,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00015000",
          "strike": 15,
          "currency": "USD",
          "lastPrice": 218.3,
          "change": 0,
          "percentChange": 0,
          "volume": 6,
          "openInterest": 0,
          "bid": 205.6,
          "ask": 207.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-16T16:16:43.000Z",
          "impliedVolatility": 13.796876376953126,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00050000",
          "strike": 50,
          "currency": "USD",
          "lastPrice": 164.65,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 15,
          "bid": 179.7,
          "ask": 181.9,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-06-13T19:47:00.000Z",
          "impliedVolatility": 15.714843928222656,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00080000",
          "strike": 80,
          "currency": "USD",
          "lastPrice": 147.3,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 84,
          "bid": 134.95,
          "ask": 137.45,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-11T15:06:40.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00085000",
          "strike": 85,
          "currency": "USD",
          "lastPrice": 130.38,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 0,
          "bid": 135.65,
          "ask": 137.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:42:39.000Z",
          "impliedVolatility": 5.0195349755859375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00090000",
          "strike": 90,
          "currency": "USD",
          "lastPrice": 125.39,
          "change": 0,
          "percentChange": 0,
          "volume": 20,
          "openInterest": 0,
          "bid": 130.7,
          "ask": 132.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:42:39.000Z",
          "impliedVolatility": 4.740238449707031,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00095000",
          "strike": 95,
          "currency": "USD",
          "lastPrice": 120.41,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 2,
          "bid": 125.65,
          "ask": 127.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:42:39.000Z",
          "impliedVolatility": 4.476566904296874,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00100000",
          "strike": 100,
          "currency": "USD",
          "lastPrice": 110.44,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 14,
          "bid": 120.7,
          "ask": 122.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-07T19:29:03.000Z",
          "impliedVolatility": 4.226567216796875,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00105000",
          "strike": 105,
          "currency": "USD",
          "lastPrice": 109.14,
          "change": 0,
          "percentChange": 0,
          "volume": 7,
          "openInterest": 0,
          "bid": 115.7,
          "ask": 117.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T14:35:23.000Z",
          "impliedVolatility": 4.027348715820313,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00110000",
          "strike": 110,
          "currency": "USD",
          "lastPrice": 105.5,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 8,
          "bid": 110.7,
          "ask": 112.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T15:05:11.000Z",
          "impliedVolatility": 3.761719345703125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00115000",
          "strike": 115,
          "currency": "USD",
          "lastPrice": 107.72,
          "change": 17.970001,
          "percentChange": 20.022285,
          "volume": 2,
          "openInterest": 28,
          "bid": 105.7,
          "ask": 107.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T15:37:39.000Z",
          "impliedVolatility": 3.5800791748046876,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00120000",
          "strike": 120,
          "currency": "USD",
          "lastPrice": 93.34,
          "change": 0,
          "percentChange": 0,
          "volume": 7,
          "openInterest": 46,
          "bid": 100.75,
          "ask": 102.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-08T17:10:01.000Z",
          "impliedVolatility": 3.3710953222656244,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00125000",
          "strike": 125,
          "currency": "USD",
          "lastPrice": 96.2,
          "change": 3.8799973,
          "percentChange": 4.20277,
          "volume": 10,
          "openInterest": 22,
          "bid": 95.7,
          "ask": 97.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:01:21.000Z",
          "impliedVolatility": 3.167970830078125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00130000",
          "strike": 130,
          "currency": "USD",
          "lastPrice": 83.2,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 7,
          "bid": 90.75,
          "ask": 92.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T13:37:01.000Z",
          "impliedVolatility": 2.9746119384765626,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00135000",
          "strike": 135,
          "currency": "USD",
          "lastPrice": 87.77,
          "change": 5.619995,
          "percentChange": 6.8411384,
          "volume": 2,
          "openInterest": 1,
          "bid": 85.7,
          "ask": 87.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T15:37:39.000Z",
          "impliedVolatility": 2.787112407226563,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00140000",
          "strike": 140,
          "currency": "USD",
          "lastPrice": 79.44,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 13,
          "bid": 80.75,
          "ask": 82.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T13:30:01.000Z",
          "impliedVolatility": 2.6074253564453125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00145000",
          "strike": 145,
          "currency": "USD",
          "lastPrice": 72.39,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 24,
          "bid": 75.65,
          "ask": 77.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T19:27:53.000Z",
          "impliedVolatility": 2.4062539843749997,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00150000",
          "strike": 150,
          "currency": "USD",
          "lastPrice": 71.48,
          "change": 0.83000183,
          "percentChange": 1.1748079,
          "volume": 15,
          "openInterest": 46,
          "bid": 70.75,
          "ask": 72.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:37:55.000Z",
          "impliedVolatility": 2.259769975585937,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00155000",
          "strike": 155,
          "currency": "USD",
          "lastPrice": 66.5,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 7,
          "bid": 65.75,
          "ask": 67.2,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T15:54:13.000Z",
          "impliedVolatility": 2.1152390869140625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00160000",
          "strike": 160,
          "currency": "USD",
          "lastPrice": 61,
          "change": -0.099998474,
          "percentChange": -0.16366363,
          "volume": 5,
          "openInterest": 34,
          "bid": 61.25,
          "ask": 62.5,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T13:34:41.000Z",
          "impliedVolatility": 2.208988852539062,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00165000",
          "strike": 165,
          "currency": "USD",
          "lastPrice": 56.48,
          "change": 0.45000076,
          "percentChange": 0.80314255,
          "volume": 1,
          "openInterest": 18,
          "bid": 55.95,
          "ask": 57.6,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:15:45.000Z",
          "impliedVolatility": 1.9814454052734376,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00170000",
          "strike": 170,
          "currency": "USD",
          "lastPrice": 51.1,
          "change": 0.32999802,
          "percentChange": 0.64998627,
          "volume": 2,
          "openInterest": 193,
          "bid": 51.3,
          "ask": 52.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T16:43:29.000Z",
          "impliedVolatility": 1.8505866845703123,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00175000",
          "strike": 175,
          "currency": "USD",
          "lastPrice": 46.08,
          "change": 0.08000183,
          "percentChange": 0.17391703,
          "volume": 7,
          "openInterest": 1175,
          "bid": 46.3,
          "ask": 47.6,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T16:44:03.000Z",
          "impliedVolatility": 1.7275404248046877,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00180000",
          "strike": 180,
          "currency": "USD",
          "lastPrice": 41.63,
          "change": 0.63000107,
          "percentChange": 1.536588,
          "volume": 20,
          "openInterest": 3078,
          "bid": 41.55,
          "ask": 41.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:28:39.000Z",
          "impliedVolatility": 1.4287137939453123,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00185000",
          "strike": 185,
          "currency": "USD",
          "lastPrice": 36.57,
          "change": 0.36999893,
          "percentChange": 1.0220965,
          "volume": 48,
          "openInterest": 9264,
          "bid": 36.55,
          "ask": 36.75,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:09:39.000Z",
          "impliedVolatility": 1.272464575195312,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00187500",
          "strike": 187.5,
          "currency": "USD",
          "lastPrice": 30.21,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 23,
          "bid": 33.8,
          "ask": 34.95,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T15:36:18.000Z",
          "impliedVolatility": 1.284671545410156,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00190000",
          "strike": 190,
          "currency": "USD",
          "lastPrice": 31.66,
          "change": 0.5100002,
          "percentChange": 1.6372399,
          "volume": 138,
          "openInterest": 21269,
          "bid": 31.55,
          "ask": 31.8,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:21:32.000Z",
          "impliedVolatility": 1.12891060546875,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00195000",
          "strike": 195,
          "currency": "USD",
          "lastPrice": 26.68,
          "change": 0.55000114,
          "percentChange": 2.1048648,
          "volume": 152,
          "openInterest": 25710,
          "bid": 26.55,
          "ask": 26.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:48:26.000Z",
          "impliedVolatility": 0.983398603515625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00197500",
          "strike": 197.5,
          "currency": "USD",
          "lastPrice": 24.1,
          "change": 1.0500011,
          "percentChange": 4.55532,
          "volume": 11,
          "openInterest": 483,
          "bid": 23.95,
          "ask": 24.3,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:52:49.000Z",
          "impliedVolatility": 0.8793957373046875,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00200000",
          "strike": 200,
          "currency": "USD",
          "lastPrice": 21.7,
          "change": 0.6500015,
          "percentChange": 3.0878932,
          "volume": 397,
          "openInterest": 13963,
          "bid": 21.6,
          "ask": 21.8,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:12.000Z",
          "impliedVolatility": 0.8276384423828124,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00202500",
          "strike": 202.5,
          "currency": "USD",
          "lastPrice": 18.84,
          "change": 0.40999985,
          "percentChange": 2.224633,
          "volume": 5,
          "openInterest": 1444,
          "bid": 19,
          "ask": 19.25,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:11:50.000Z",
          "impliedVolatility": 0.726565234375,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00205000",
          "strike": 205,
          "currency": "USD",
          "lastPrice": 16.8,
          "change": 0.29999924,
          "percentChange": 1.851847,
          "volume": 467,
          "openInterest": 12024,
          "bid": 16.6,
          "ask": 16.8,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:30:29.000Z",
          "impliedVolatility": 0.6704134521484376,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00207500",
          "strike": 207.5,
          "currency": "USD",
          "lastPrice": 14.05,
          "change": 0.6999998,
          "percentChange": 5.2434444,
          "volume": 62,
          "openInterest": 2200,
          "bid": 14.05,
          "ask": 14.3,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:08:57.000Z",
          "impliedVolatility": 0.5839885351562499,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00210000",
          "strike": 210,
          "currency": "USD",
          "lastPrice": 11.72,
          "change": 0.07999992,
          "percentChange": 0.6872845,
          "volume": 3620,
          "openInterest": 30040,
          "bid": 11.6,
          "ask": 11.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:25:38.000Z",
          "impliedVolatility": 0.5151415673828125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00212500",
          "strike": 212.5,
          "currency": "USD",
          "lastPrice": 9.2,
          "change": 0.03999996,
          "percentChange": 0.43668082,
          "volume": 160,
          "openInterest": 3574,
          "bid": 9.2,
          "ask": 9.4,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:27:17.000Z",
          "impliedVolatility": 0.46631393066406257,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00215000",
          "strike": 215,
          "currency": "USD",
          "lastPrice": 6.85,
          "change": 0,
          "percentChange": 0,
          "volume": 11523,
          "openInterest": 34753,
          "bid": 6.75,
          "ask": 6.9,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:29:39.000Z",
          "impliedVolatility": 0.37500625,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00217500",
          "strike": 217.5,
          "currency": "USD",
          "lastPrice": 4.62,
          "change": -0.09000015,
          "percentChange": -1.9108312,
          "volume": 2247,
          "openInterest": 8898,
          "bid": 4.5,
          "ask": 4.6,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:31:26.000Z",
          "impliedVolatility": 0.30762411132812495,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00220000",
          "strike": 220,
          "currency": "USD",
          "lastPrice": 2.68,
          "change": -0.31999993,
          "percentChange": -10.561053,
          "volume": 21546,
          "openInterest": 38417,
          "bid": 2.64,
          "ask": 2.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:39.000Z",
          "impliedVolatility": 0.2690502783203125,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816C00222500",
          "strike": 222.5,
          "currency": "USD",
          "lastPrice": 1.26,
          "change": -0.39,
          "percentChange": -23.636364,
          "volume": 64013,
          "openInterest": 12653,
          "bid": 1.24,
          "ask": 1.26,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:40.000Z",
          "impliedVolatility": 0.2375564526367187,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00225000",
          "strike": 225,
          "currency": "USD",
          "lastPrice": 0.43,
          "change": -0.32999998,
          "percentChange": -42.307693,
          "volume": 49339,
          "openInterest": 51700,
          "bid": 0.43,
          "ask": 0.45,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:55.000Z",
          "impliedVolatility": 0.21949022705078125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00227500",
          "strike": 227.5,
          "currency": "USD",
          "lastPrice": 0.12,
          "change": -0.19,
          "percentChange": -61.29032,
          "volume": 22865,
          "openInterest": 11430,
          "bid": 0.11,
          "ask": 0.12,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:31:08.000Z",
          "impliedVolatility": 0.20996883789062498,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00230000",
          "strike": 230,
          "currency": "USD",
          "lastPrice": 0.04,
          "change": -0.089999996,
          "percentChange": -69.230774,
          "volume": 11208,
          "openInterest": 58949,
          "bid": 0.03,
          "ask": 0.04,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:30:11.000Z",
          "impliedVolatility": 0.22071091796874998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00232500",
          "strike": 232.5,
          "currency": "USD",
          "lastPrice": 0.02,
          "change": -0.030000001,
          "percentChange": -60,
          "volume": 4508,
          "openInterest": 5354,
          "bid": 0.01,
          "ask": 0.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:23:47.000Z",
          "impliedVolatility": 0.2461012890625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00235000",
          "strike": 235,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": -0.02,
          "percentChange": -66.66667,
          "volume": 5405,
          "openInterest": 32465,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:22:58.000Z",
          "impliedVolatility": 0.26563234375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00237500",
          "strike": 237.5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 469,
          "openInterest": 2203,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T16:41:49.000Z",
          "impliedVolatility": 0.304694453125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00240000",
          "strike": 240,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 997,
          "openInterest": 31697,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:05:18.000Z",
          "impliedVolatility": 0.3437565625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00242500",
          "strike": 242.5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 3,
          "openInterest": 1296,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:10:34.000Z",
          "impliedVolatility": 0.38281867187499996,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00245000",
          "strike": 245,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 70,
          "openInterest": 18063,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:01:21.000Z",
          "impliedVolatility": 0.42188078125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00250000",
          "strike": 250,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 331,
          "openInterest": 45030,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:35:12.000Z",
          "impliedVolatility": 0.500005,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00255000",
          "strike": 255,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 46,
          "openInterest": 7074,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:01:08.000Z",
          "impliedVolatility": 0.5312546875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00260000",
          "strike": 260,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 12990,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:34:02.000Z",
          "impliedVolatility": 0.5937540625000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00265000",
          "strike": 265,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 9,
          "openInterest": 1849,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:01:19.000Z",
          "impliedVolatility": 0.6562534375000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00270000",
          "strike": 270,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 85,
          "openInterest": 3531,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:28:27.000Z",
          "impliedVolatility": 0.7187528125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00275000",
          "strike": 275,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 3294,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T14:27:46.000Z",
          "impliedVolatility": 0.7812521875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00280000",
          "strike": 280,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 25,
          "openInterest": 1956,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:42:00.000Z",
          "impliedVolatility": 0.8437515624999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00285000",
          "strike": 285,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 645,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T18:34:24.000Z",
          "impliedVolatility": 0.9062509375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00290000",
          "strike": 290,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 20,
          "openInterest": 2862,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:42:00.000Z",
          "impliedVolatility": 0.937500625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00295000",
          "strike": 295,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 271,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T16:41:45.000Z",
          "impliedVolatility": 1.000005,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00300000",
          "strike": 300,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 4230,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:48:58.000Z",
          "impliedVolatility": 1.0625046875000002,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00305000",
          "strike": 305,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 152,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:49:02.000Z",
          "impliedVolatility": 1.125004375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00310000",
          "strike": 310,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 363,
          "openInterest": 1568,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-02T19:40:41.000Z",
          "impliedVolatility": 1.15625421875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00315000",
          "strike": 315,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 578,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:49:05.000Z",
          "impliedVolatility": 1.21875390625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00320000",
          "strike": 320,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 2343,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T16:23:25.000Z",
          "impliedVolatility": 1.2500037499999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00330000",
          "strike": 330,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1534,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T13:30:09.000Z",
          "impliedVolatility": 1.3750031249999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00340000",
          "strike": 340,
          "currency": "USD",
          "lastPrice": 0.06,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 3953,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-02T17:02:29.000Z",
          "impliedVolatility": 1.4375028125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00350000",
          "strike": 350,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": -0.19,
          "percentChange": -95,
          "volume": 1,
          "openInterest": 1194,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T15:11:51.000Z",
          "impliedVolatility": 1.5312523437499999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00360000",
          "strike": 360,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1326,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T13:30:01.000Z",
          "impliedVolatility": 1.625001875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816C00370000",
          "strike": 370,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 3,
          "openInterest": 5923,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T13:37:36.000Z",
          "impliedVolatility": 1.6875015625,
          "inTheMoney": false
        }
      ],
      "puts": [
        {
          "contractSymbol": "AAPL240816P00005000",
          "strike": 5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 4,
          "openInterest": 5,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T13:30:05.000Z",
          "impliedVolatility": 13.000001875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00015000",
          "strike": 15,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "openInterest": 126,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T14:33:15.000Z",
          "impliedVolatility": 9.375004140625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00020000",
          "strike": 20,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-03-22T13:38:52.000Z",
          "impliedVolatility": 7.87500015625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00025000",
          "strike": 25,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 3,
          "openInterest": 4,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-05-14T19:13:50.000Z",
          "impliedVolatility": 7.2500009375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00045000",
          "strike": 45,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 40,
          "openInterest": 40,
          "bid": 0,
          "ask": 0.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-03-14T13:30:04.000Z",
          "impliedVolatility": 5.9687525390625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00050000",
          "strike": 50,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 250,
          "openInterest": 188,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T19:39:20.000Z",
          "impliedVolatility": 4.875003906249999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00080000",
          "strike": 80,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 309,
          "openInterest": 620,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T14:16:22.000Z",
          "impliedVolatility": 3.3750015624999996,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00085000",
          "strike": 85,
          "currency": "USD",
          "lastPrice": 0.02,
          "change": 0,
          "percentChange": 0,
          "volume": 3,
          "openInterest": 721,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T19:12:03.000Z",
          "impliedVolatility": 3.1875020312499998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00090000",
          "strike": 90,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": 0,
          "percentChange": 0,
          "volume": 82,
          "openInterest": 547,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T14:14:14.000Z",
          "impliedVolatility": 3.0000025,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00095000",
          "strike": 95,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 4,
          "openInterest": 1358,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-07T13:30:07.000Z",
          "impliedVolatility": 2.8750028125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00100000",
          "strike": 100,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 2495,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T13:34:42.000Z",
          "impliedVolatility": 2.68750328125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00105000",
          "strike": 105,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 10,
          "openInterest": 5845,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-08T16:22:07.000Z",
          "impliedVolatility": 2.50000375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00110000",
          "strike": 110,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 3050,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T17:17:52.000Z",
          "impliedVolatility": 2.3750040624999995,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00115000",
          "strike": 115,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 330,
          "openInterest": 4006,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T14:01:20.000Z",
          "impliedVolatility": 2.2500043749999996,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00120000",
          "strike": 120,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 4,
          "openInterest": 2544,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T14:02:07.000Z",
          "impliedVolatility": 2.0625048437499998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00125000",
          "strike": 125,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 3433,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T18:12:24.000Z",
          "impliedVolatility": 1.9375003125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00130000",
          "strike": 130,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 4228,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T13:31:12.000Z",
          "impliedVolatility": 1.8125009374999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00135000",
          "strike": 135,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 5,
          "openInterest": 3088,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T15:12:37.000Z",
          "impliedVolatility": 1.6875015625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00140000",
          "strike": 140,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 15,
          "openInterest": 7457,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T13:30:01.000Z",
          "impliedVolatility": 1.5625021874999998,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00145000",
          "strike": 145,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 41,
          "openInterest": 4333,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T14:37:36.000Z",
          "impliedVolatility": 1.46875265625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00150000",
          "strike": 150,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 20,
          "openInterest": 9955,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:23:28.000Z",
          "impliedVolatility": 1.3750031249999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00155000",
          "strike": 155,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 11,
          "openInterest": 5715,
          "bid": 0,
          "ask": 0,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T14:52:38.000Z",
          "impliedVolatility": 0.500005,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00160000",
          "strike": 160,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 7,
          "openInterest": 7982,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T15:07:37.000Z",
          "impliedVolatility": 1.15625421875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00165000",
          "strike": 165,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 16,
          "openInterest": 12525,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:26:23.000Z",
          "impliedVolatility": 1.0312548437500002,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00170000",
          "strike": 170,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 21,
          "openInterest": 13941,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T16:21:26.000Z",
          "impliedVolatility": 0.937500625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00175000",
          "strike": 175,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 67,
          "openInterest": 10913,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T15:26:27.000Z",
          "impliedVolatility": 0.8437515624999999,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00180000",
          "strike": 180,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": 0,
          "percentChange": 0,
          "volume": 1735,
          "openInterest": 47001,
          "bid": 0,
          "ask": 0.01,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:43.000Z",
          "impliedVolatility": 0.7500025,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00185000",
          "strike": 185,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": -0.02,
          "percentChange": -66.66667,
          "volume": 572,
          "openInterest": 28382,
          "bid": 0.01,
          "ask": 0.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:15.000Z",
          "impliedVolatility": 0.73437765625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00187500",
          "strike": 187.5,
          "currency": "USD",
          "lastPrice": 0.01,
          "change": -0.02,
          "percentChange": -66.66667,
          "volume": 60,
          "openInterest": 4105,
          "bid": 0.02,
          "ask": 0.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:29:48.000Z",
          "impliedVolatility": 0.70312796875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00190000",
          "strike": 190,
          "currency": "USD",
          "lastPrice": 0.02,
          "change": -0.02,
          "percentChange": -50,
          "volume": 12082,
          "openInterest": 43303,
          "bid": 0.02,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:29:22.000Z",
          "impliedVolatility": 0.6679720703125002,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00192500",
          "strike": 192.5,
          "currency": "USD",
          "lastPrice": 0.02,
          "change": -0.02,
          "percentChange": -50,
          "volume": 137,
          "openInterest": 1604,
          "bid": 0.02,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:26:53.000Z",
          "impliedVolatility": 0.6171913281250001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00195000",
          "strike": 195,
          "currency": "USD",
          "lastPrice": 0.02,
          "change": -0.030000001,
          "percentChange": -75,
          "volume": 879,
          "openInterest": 26217,
          "bid": 0.02,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:23:49.000Z",
          "impliedVolatility": 0.5625043750000001,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00197500",
          "strike": 197.5,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": -0.03,
          "percentChange": -50,
          "volume": 260,
          "openInterest": 5401,
          "bid": 0.02,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:02:21.000Z",
          "impliedVolatility": 0.51562984375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00200000",
          "strike": 200,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": -0.04,
          "percentChange": -66.66667,
          "volume": 4660,
          "openInterest": 35843,
          "bid": 0.02,
          "ask": 0.03,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:28:33.000Z",
          "impliedVolatility": 0.4726615234375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00202500",
          "strike": 202.5,
          "currency": "USD",
          "lastPrice": 0.03,
          "change": -0.060000002,
          "percentChange": -66.666664,
          "volume": 357,
          "openInterest": 10227,
          "bid": 0.03,
          "ask": 0.04,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:23:26.000Z",
          "impliedVolatility": 0.437505625,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00205000",
          "strike": 205,
          "currency": "USD",
          "lastPrice": 0.04,
          "change": -0.07,
          "percentChange": -70,
          "volume": 2973,
          "openInterest": 30693,
          "bid": 0.03,
          "ask": 0.04,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:28:08.000Z",
          "impliedVolatility": 0.38281867187499996,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00207500",
          "strike": 207.5,
          "currency": "USD",
          "lastPrice": 0.05,
          "change": -0.10000001,
          "percentChange": -66.66667,
          "volume": 1293,
          "openInterest": 9494,
          "bid": 0.04,
          "ask": 0.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:31:09.000Z",
          "impliedVolatility": 0.34180345703125,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00210000",
          "strike": 210,
          "currency": "USD",
          "lastPrice": 0.07,
          "change": -0.13999999,
          "percentChange": -69.99999,
          "volume": 15348,
          "openInterest": 44649,
          "bid": 0.05,
          "ask": 0.07,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:31:57.000Z",
          "impliedVolatility": 0.301764794921875,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00212500",
          "strike": 212.5,
          "currency": "USD",
          "lastPrice": 0.09,
          "change": -0.24000001,
          "percentChange": -72.72727,
          "volume": 6957,
          "openInterest": 12251,
          "bid": 0.09,
          "ask": 0.1,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:28:54.000Z",
          "impliedVolatility": 0.25977302734375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00215000",
          "strike": 215,
          "currency": "USD",
          "lastPrice": 0.18,
          "change": -0.34999996,
          "percentChange": -66.037735,
          "volume": 34598,
          "openInterest": 29269,
          "bid": 0.18,
          "ask": 0.19,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:20.000Z",
          "impliedVolatility": 0.22852333984375,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00217500",
          "strike": 217.5,
          "currency": "USD",
          "lastPrice": 0.44,
          "change": -0.47000003,
          "percentChange": -51.648354,
          "volume": 24526,
          "openInterest": 8780,
          "bid": 0.42,
          "ask": 0.44,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:58.000Z",
          "impliedVolatility": 0.20606262695312497,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00220000",
          "strike": 220,
          "currency": "USD",
          "lastPrice": 0.99,
          "change": -0.65999997,
          "percentChange": -40,
          "volume": 53760,
          "openInterest": 20620,
          "bid": 1,
          "ask": 1.02,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:32:24.000Z",
          "impliedVolatility": 0.18531088134765622,
          "inTheMoney": false
        },
        {
          "contractSymbol": "AAPL240816P00222500",
          "strike": 222.5,
          "currency": "USD",
          "lastPrice": 2.07,
          "change": -0.72,
          "percentChange": -25.806452,
          "volume": 12283,
          "openInterest": 1673,
          "bid": 2.07,
          "ask": 2.14,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:30:50.000Z",
          "impliedVolatility": 0.15869981933593752,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00225000",
          "strike": 225,
          "currency": "USD",
          "lastPrice": 3.81,
          "change": -0.53999996,
          "percentChange": -12.413793,
          "volume": 1750,
          "openInterest": 12298,
          "bid": 3.8,
          "ask": 3.9,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:24:47.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00227500",
          "strike": 227.5,
          "currency": "USD",
          "lastPrice": 6.48,
          "change": -0.009999752,
          "percentChange": -0.1540794,
          "volume": 259,
          "openInterest": 683,
          "bid": 5.9,
          "ask": 6.15,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:01:04.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00230000",
          "strike": 230,
          "currency": "USD",
          "lastPrice": 8.51,
          "change": -1.0799999,
          "percentChange": -11.26173,
          "volume": 281,
          "openInterest": 3538,
          "bid": 8.25,
          "ask": 8.55,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:24:47.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00232500",
          "strike": 232.5,
          "currency": "USD",
          "lastPrice": 11.25,
          "change": -0.15999985,
          "percentChange": -1.4022774,
          "volume": 26,
          "openInterest": 16,
          "bid": 10.65,
          "ask": 11.25,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:15:21.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00235000",
          "strike": 235,
          "currency": "USD",
          "lastPrice": 13.4,
          "change": -0.45000076,
          "percentChange": -3.2491028,
          "volume": 2045,
          "openInterest": 2057,
          "bid": 13.35,
          "ask": 13.6,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:34:30.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00237500",
          "strike": 237.5,
          "currency": "USD",
          "lastPrice": 20.46,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 0,
          "bid": 15.8,
          "ask": 16.5,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-12T19:29:59.000Z",
          "impliedVolatility": 0.35156898437499995,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00240000",
          "strike": 240,
          "currency": "USD",
          "lastPrice": 18.66,
          "change": -0.59000015,
          "percentChange": -3.064936,
          "volume": 30,
          "openInterest": 253,
          "bid": 17.95,
          "ask": 18.6,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T18:06:40.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00242500",
          "strike": 242.5,
          "currency": "USD",
          "lastPrice": 21.35,
          "change": -8.58,
          "percentChange": -28.66689,
          "volume": 9,
          "openInterest": 4,
          "bid": 20.7,
          "ask": 21.25,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T17:20:46.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00245000",
          "strike": 245,
          "currency": "USD",
          "lastPrice": 24,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1,
          "bid": 22.9,
          "ask": 23.8,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-13T18:06:26.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00250000",
          "strike": 250,
          "currency": "USD",
          "lastPrice": 28.54,
          "change": -3.459999,
          "percentChange": -10.812497,
          "volume": 2,
          "openInterest": 0,
          "bid": 28.25,
          "ask": 28.65,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-14T14:47:24.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00255000",
          "strike": 255,
          "currency": "USD",
          "lastPrice": 39.95,
          "change": 0,
          "percentChange": 0,
          "volume": 1,
          "openInterest": 1,
          "bid": 33.35,
          "ask": 33.7,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-09T19:55:23.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00260000",
          "strike": 260,
          "currency": "USD",
          "lastPrice": 50.75,
          "change": 0,
          "percentChange": 0,
          "volume": 55,
          "openInterest": 0,
          "bid": 38.3,
          "ask": 38.65,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T18:40:15.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00270000",
          "strike": 270,
          "currency": "USD",
          "lastPrice": 47.7,
          "change": 0,
          "percentChange": 0,
          "openInterest": 0,
          "bid": 48.1,
          "ask": 48.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-31T19:54:43.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00275000",
          "strike": 275,
          "currency": "USD",
          "lastPrice": 41.03,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 0,
          "bid": 52.85,
          "ask": 53.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-15T19:46:03.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00290000",
          "strike": 290,
          "currency": "USD",
          "lastPrice": 77,
          "change": 0,
          "percentChange": 0,
          "bid": 67.85,
          "ask": 68.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-05T15:23:48.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00330000",
          "strike": 330,
          "currency": "USD",
          "lastPrice": 107.25,
          "change": 0,
          "percentChange": 0,
          "volume": 2,
          "openInterest": 0,
          "bid": 108.25,
          "ask": 108.85,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-07-31T18:59:38.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00340000",
          "strike": 340,
          "currency": "USD",
          "lastPrice": 119.45,
          "change": 0,
          "percentChange": 0,
          "openInterest": 0,
          "bid": 117.9,
          "ask": 118.95,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-08-01T15:35:09.000Z",
          "impliedVolatility": 0.000010000000000000003,
          "inTheMoney": true
        },
        {
          "contractSymbol": "AAPL240816P00370000",
          "strike": 370,
          "currency": "USD",
          "lastPrice": 159.85,
          "change": 0,
          "percentChange": 0,
          "openInterest": 0,
          "bid": 151.75,
          "ask": 153.05,
          "contractSize": "REGULAR",
          "expiration": "2024-08-16T00:00:00.000Z",
          "lastTradeDate": "2024-06-25T18:14:36.000Z",
          "impliedVolatility": 3.956543077392578,
          "inTheMoney": true
        }
      ]
    }
  ]
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Options data for symbol AAPL not found",
  "error": "Not Found"
}