### Request ###

GET /yahoo-finance/quote?symbol=AAPL HTTP/1.1
Host: localhost:3000

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 2560
ETag: W/"a00-nCIilyXB3S3PM+vUi7rAr22/vLM"
Date: Tue, 13 Aug 2024 22:27:23 GMT
Connection: close

{
  "language": "en-US",
  "region": "US",
  "quoteType": "EQUITY",
  "typeDisp": "Equity",
  "quoteSourceName": "Nasdaq Real Time Price",
  "triggerable": true,
  "customPriceAlertConfidence": "HIGH",
  "postMarketChangePercent": -0.21602423,
  "postMarketTime": "2024-08-13T22:27:08.000Z",
  "postMarketPrice": 220.792,
  "postMarketChange": -0.47799683,
  "regularMarketChange": 3.7400055,
  "regularMarketTime": "2024-08-13T20:00:01.000Z",
  "regularMarketDayHigh": 221.89,
  "regularMarketDayRange": {
    "low": 219.01,
    "high": 221.89
  },
  "regularMarketDayLow": 219.01,
  "regularMarketVolume": 41453325,
  "regularMarketPreviousClose": 217.53,
  "bid": 221.04,
  "ask": 221.18,
  "bidSize": 1,
  "askSize": 1,
  "fullExchangeName": "NasdaqGS",
  "financialCurrency": "USD",
  "regularMarketOpen": 219.105,
  "averageDailyVolume3Month": 65826293,
  "averageDailyVolume10Day": 63983030,
  "fiftyTwoWeekLowChange": 57.190002,
  "fiftyTwoWeekLowChangePercent": 0.3485495,
  "fiftyTwoWeekRange": {
    "low": 164.08,
    "high": 237.23
  },
  "fiftyTwoWeekHighChange": -15.959991,
  "fiftyTwoWeekHighChangePercent": -0.06727645,
  "fiftyTwoWeekLow": 164.08,
  "fiftyTwoWeekHigh": 237.23,
  "fiftyTwoWeekChangePercent": 22.586643,
  "dividendDate": "2024-08-15T00:00:00.000Z",
  "earningsTimestamp": "2024-08-01T20:30:00.000Z",
  "earningsTimestampStart": "2024-10-31T10:59:00.000Z",
  "earningsTimestampEnd": "2024-11-04T12:00:00.000Z",
  "earningsCallTimestampStart": 1722546000,
  "earningsCallTimestampEnd": 1722546000,
  "isEarningsDateEstimate": true,
  "trailingAnnualDividendRate": 0.97,
  "trailingPE": 33.678844,
  "dividendRate": 1,
  "trailingAnnualDividendYield": 0.0044591553,
  "dividendYield": 0.46,
  "epsTrailingTwelveMonths": 6.57,
  "epsForward": 6.85,
  "epsCurrentYear": 6.13,
  "priceEpsCurrentYear": 36.09625,
  "sharesOutstanding": 15204100096,
  "bookValue": 4.382,
  "fiftyDayAverage": 215.2808,
  "fiftyDayAverageChange": 5.989197,
  "fiftyDayAverageChangePercent": 0.027820393,
  "twoHundredDayAverage": 190.6497,
  "twoHundredDayAverageChange": 30.6203,
  "twoHundredDayAverageChangePercent": 0.16061027,
  "marketCap": 3364211392512,
  "forwardPE": 32.302193,
  "priceToBook": 50.49521,
  "sourceInterval": 15,
  "exchangeDataDelayedBy": 0,
  "averageAnalystRating": "2.0 - Buy",
  "currency": "USD",
  "exchange": "NMS",
  "shortName": "Apple Inc.",
  "longName": "Apple Inc.",
  "messageBoardId": "finmb_24937",
  "exchangeTimezoneName": "America/New_York",
  "exchangeTimezoneShortName": "EDT",
  "gmtOffSetMilliseconds": -14400000,
  "market": "us_market",
  "esgPopulated": false,
  "regularMarketPrice": 221.27,
  "regularMarketChangePercent": 1.7193056,
  "marketState": "POST",
  "hasPrePostMarketData": true,
  "firstTradeDateMilliseconds": "1980-12-12T14:30:00.000Z",
  "priceHint": 2,
  "tradeable": false,
  "cryptoTradeable": false,
  "displayName": "Apple",
  "symbol": "AAPL"
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Quote for symbol AAPL not found",
  "error": "Not Found"
}