### Request ###

GET /yahoo-finance/quote?symbol=AAPL HTTP/1.1
Host: localhost:3010

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 24
X-RateLimit-Reset: 60
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 9
X-RateLimit-Reset-short: 60
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 69
X-RateLimit-Reset-longer: 60
Content-Type: application/json; charset=utf-8
Content-Length: 2430
ETag: W/"97e-COgeT+SuaLGWQnVXNYzECmnmu00"
Date: Wed, 14 Aug 2024 18:49:04 GMT
Connection: close

{
  "language": "en-US",
  "region": "US",
  "quoteType": "EQUITY",
  "typeDisp": "Equity",
  "quoteSourceName": "Nasdaq Real Time Price",
  "triggerable": true,
  "customPriceAlertConfidence": "HIGH",
  "currency": "USD",
  "exchange": "NMS",
  "shortName": "Apple Inc.",
  "longName": "Apple Inc.",
  "messageBoardId": "finmb_24937",
  "exchangeTimezoneName": "America/New_York",
  "exchangeTimezoneShortName": "EDT",
  "gmtOffSetMilliseconds": -14400000,
  "market": "us_market",
  "esgPopulated": false,
  "regularMarketChangePercent": -0.11072914,
  "regularMarketPrice": 221.025,
  "marketState": "REGULAR",
  "epsCurrentYear": 6.7,
  "priceEpsCurrentYear": 32.988808,
  "sharesOutstanding": 15204100096,
  "bookValue": 4.382,
  "fiftyDayAverage": 215.8612,
  "fiftyDayAverageChange": 5.163788,
  "fiftyDayAverageChangePercent": 0.023921797,
  "twoHundredDayAverage": 190.90054,
  "twoHundredDayAverageChange": 30.12445,
  "twoHundredDayAverageChangePercent": 0.1578018,
  "marketCap": 3360486064128,
  "forwardPE": 29.548796,
  "priceToBook": 50.439297,
  "sourceInterval": 15,
  "exchangeDataDelayedBy": 0,
  "averageAnalystRating": "2.0 - Buy",
  "tradeable": false,
  "cryptoTradeable": false,
  "regularMarketChange": -0.24501038,
  "regularMarketTime": "2024-08-14T18:49:03.000Z",
  "regularMarketDayHigh": 223.03,
  "regularMarketDayRange": {
    "low": 219.7,
    "high": 223.03
  },
  "regularMarketDayLow": 219.7,
  "regularMarketVolume": 26415709,
  "regularMarketPreviousClose": 221.27,
  "bid": 209.42,
  "ask": 221.28,
  "bidSize": 1,
  "askSize": 1,
  "fullExchangeName": "NasdaqGS",
  "financialCurrency": "USD",
  "regularMarketOpen": 220.565,
  "averageDailyVolume3Month": 65693027,
  "averageDailyVolume10Day": 64231760,
  "fiftyTwoWeekLowChange": 56.944992,
  "fiftyTwoWeekLowChangePercent": 0.34705627,
  "fiftyTwoWeekRange": {
    "low": 164.08,
    "high": 237.23
  },
  "fiftyTwoWeekHighChange": -16.205002,
  "fiftyTwoWeekHighChangePercent": -0.06830925,
  "fiftyTwoWeekLow": 164.08,
  "fiftyTwoWeekHigh": 237.23,
  "fiftyTwoWeekChangePercent": 25.315739,
  "dividendDate": "2024-08-15T00:00:00.000Z",
  "earningsTimestamp": "2024-08-01T20:30:00.000Z",
  "earningsTimestampStart": "2024-10-31T10:59:00.000Z",
  "earningsTimestampEnd": "2024-11-04T12:00:00.000Z",
  "earningsCallTimestampStart": 1722546000,
  "earningsCallTimestampEnd": 1722546000,
  "isEarningsDateEstimate": true,
  "trailingAnnualDividendRate": 0.97,
  "trailingPE": 33.641552,
  "dividendRate": 1,
  "trailingAnnualDividendYield": 0.0043837847,
  "dividendYield": 0.45,
  "epsTrailingTwelveMonths": 6.57,
  "epsForward": 7.48,
  "hasPrePostMarketData": true,
  "firstTradeDateMilliseconds": "1980-12-12T14:30:00.000Z",
  "priceHint": 2,
  "displayName": "Apple",
  "symbol": "AAPL"
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Quote for symbol AAPL not found",
  "error": "Not Found"
}