### Request ###

GET /yahoo-finance/recommendations?symbol=AAPL HTTP/1.1
Host: localhost:3000

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 24
X-RateLimit-Reset: 60
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 9
X-RateLimit-Reset-short: 60
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 69
X-RateLimit-Reset-longer: 60
Content-Type: application/json; charset=utf-8
Content-Length: 215
ETag: W/"d7-qOdnstMQ55266uV/7I7exZJGc7w"
Date: Wed, 14 Aug 2024 18:49:20 GMT
Connection: close

{
  "symbol": "AAPL",
  "recommendedSymbols": [
    {
      "symbol": "AMZN",
      "score": 0.318321
    },
    {
      "symbol": "TSLA",
      "score": 0.298744
    },
    {
      "symbol": "GOOG",
      "score": 0.281698
    },
    {
      "symbol": "META",
      "score": 0.269887
    },
    {
      "symbol": "MSFT",
      "score": 0.219035
    }
  ]
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Recommendations for symbol AAPL not found",
  "error": "Not Found"
}