### Request ###

GET /yahoo-finance/search?query=Apple&quotesCount=2&newsCount=2 HTTP/1.1
Host: localhost:3000

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 24
X-RateLimit-Reset: 60
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 9
X-RateLimit-Reset-short: 60
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 69
X-RateLimit-Reset-longer: 60
Content-Type: application/json; charset=utf-8
Content-Length: 2542
ETag: W/"9ee-8f4XqcLsKIZ8z7GShHgMZmU793k"
Date: Wed, 14 Aug 2024 18:49:43 GMT
Connection: close

{
  "explains": [],
  "count": 6,
  "quotes": [
    {
      "exchange": "NMS",
      "shortname": "Apple Inc.",
      "quoteType": "EQUITY",
      "symbol": "AAPL",
      "index": "quotes",
      "score": 55203,
      "typeDisp": "Equity",
      "longname": "Apple Inc.",
      "exchDisp": "NASDAQ",
      "sector": "Technology",
      "sectorDisp": "Technology",
      "industry": "Consumer Electronics",
      "industryDisp": "Consumer Electronics",
      "dispSecIndFlag": true,
      "isYahooFinance": true
    },
    {
      "exchange": "NYQ",
      "shortname": "Apple Hospitality REIT, Inc.",
      "quoteType": "EQUITY",
      "symbol": "APLE",
      "index": "quotes",
      "score": 20080,
      "typeDisp": "Equity",
      "longname": "Apple Hospitality REIT, Inc.",
      "exchDisp": "NYSE",
      "sector": "Real Estate",
      "sectorDisp": "Real Estate",
      "industry": "REIT—Hotel & Motel",
      "industryDisp": "REIT—Hotel & Motel",
      "isYahooFinance": true
    },
    {
      "index": "d8c1b54896db4e148d5bff7bdd4778d0",
      "name": "Apple Tree Partners",
      "permalink": "apple-tree-partners",
      "isYahooFinance": false
    },
    {
      "index": "902d61b27b7039fda61fc3a9dc44fe1a",
      "name": "Applecart",
      "permalink": "project-applecart",
      "isYahooFinance": false
    }
  ],
  "news": [
    {
      "uuid": "ef0d5476-3fe8-3808-8e92-81583f91c11a",
      "title": "Apple to Let Third Parties Use iPhone Payment Chip for Transactions",
      "publisher": "MT Newswires",
      "link": "https://finance.yahoo.com/news/apple-let-third-parties-iphone-163239762.html",
      "providerPublishTime": "2024-08-14T16:32:39.000Z",
      "type": "STORY",
      "relatedTickers": [
        "AAPL"
      ]
    },
    {
      "uuid": "3b1553d1-e890-43f7-a69a-b72f4be29b5b",
      "title": "Apple is finally opening up NFC to third-party developers in iOS 18.1",
      "publisher": "Engadget",
      "link": "https://finance.yahoo.com/m/3b1553d1-e890-43f7-a69a-b72f4be29b5b/apple-is-finally-opening-up.html",
      "providerPublishTime": "2024-08-14T16:40:28.000Z",
      "type": "STORY",
      "thumbnail": {
        "resolutions": [
          {
            "url": "https://s.yimg.com/uu/api/res/1.2/MnBN1nE2nGoYeVjy5GzBKA--~B/aD02MzA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2024-08/dfde9ec0-5a5a-11ef-9fff-5f8f40d36d5c",
            "width": 1200,
            "height": 630,
            "tag": "original"
          },
          {
            "url": "https://s.yimg.com/uu/api/res/1.2/O.QVlSZswqH7tCM6UD.VJQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2024-08/dfde9ec0-5a5a-11ef-9fff-5f8f40d36d5c",
            "width": 140,
            "height": 140,
            "tag": "140x140"
          }
        ]
      }
    }
  ],
  "nav": [],
  "lists": [],
  "researchReports": [],
  "screenerFieldResults": [],
  "totalTime": 107,
  "timeTakenForQuotes": 435,
  "timeTakenForNews": 700,
  "timeTakenForAlgowatchlist": 400,
  "timeTakenForPredefinedScreener": 400,
  "timeTakenForCrunchbase": 400,
  "timeTakenForNav": 400,
  "timeTakenForResearchReports": 0,
  "timeTakenForScreenerField": 0,
  "timeTakenForCulturalAssets": 0,
  "timeTakenForSearchLists": 0
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Search results for query Apple not found",
  "error": "Not Found"
}