### Request ###

GET /yahoo-finance/stock-image?symbol=AAPL HTTP/1.1
Host: localhost:3010

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 24
X-RateLimit-Reset: 60
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 9
X-RateLimit-Reset-short: 60
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 69
X-RateLimit-Reset-longer: 60
Content-Type: application/json; charset=utf-8
Content-Length: 69
ETag: W/"45-lQP7jY4EABad0M5Ly9eZx/XklJo"
Date: Wed, 14 Aug 2024 18:49:59 GMT
Connection: close

{
  "imageUrl": "https://financialmodelingprep.com/image-stock/AAPL.png"
}

## HTTP CODE - 200 (No image found) ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 22
X-RateLimit-Reset: 46
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 7
X-RateLimit-Reset-short: 46
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 67
X-RateLimit-Reset-longer: 46
Content-Type: application/json; charset=utf-8
Content-Length: 17
ETag: W/"11-Q9b8V1BUnoy2ekgu1QafBRoMB3w"
Date: Wed, 14 Aug 2024 18:50:15 GMT
Connection: close

{
  "imageUrl": null
}

## HTTP CODE - 500 ##

HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8

{
  "statusCode": 500,
  "message": "Failed to fetch stock image: Network error",
  "error": "Internal Server Error"
}