### Request ###

GET /yahoo-finance/trending-symbols?country=US&count=5 HTTP/1.1
Host: localhost:3000

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Length,X-Total-Count
X-RateLimit-Limit: 25
X-RateLimit-Remaining: 24
X-RateLimit-Reset: 60
X-RateLimit-Limit-short: 10
X-RateLimit-Remaining-short: 9
X-RateLimit-Reset-short: 60
X-RateLimit-Limit-longer: 70
X-RateLimit-Remaining-longer: 69
X-RateLimit-Reset-longer: 60
Content-Type: application/json; charset=utf-8
Content-Length: 168
ETag: W/"a8-Sa5+1ZUxSAXAALnZAtjIiaATJlI"
Date: Wed, 14 Aug 2024 18:50:36 GMT
Connection: close

{
  "count": 5,
  "quotes": [
    {
      "symbol": "GOOG"
    },
    {
      "symbol": "K"
    },
    {
      "symbol": "CLOV"
    },
    {
      "symbol": "GOOGL"
    },
    {
      "symbol": "SERV"
    }
  ],
  "jobTimestamp": 1723659512109,
  "startInterval": 202408141700
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{
  "statusCode": 404,
  "message": "Trending symbols for country US not found",
  "error": "Not Found"
}