### Request ###

POST /auth/application HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "appSlug": "second-app"
}

### Response ###

## HTTP CODE - 201 ##

HTTP/1.1 201 Created
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 192
ETag: W/"c0-+rXkxkcK6eM9FBiNgG+EmuoUxUY"
Date: Fri, 02 Aug 2024 20:55:31 GMT
Connection: close

{
  "id": "89b4df19-bd80-498b-bb95-186efb85829e",
  "appSlug": "first-app",
  "appIp": "::ffff:127.0.0.1",
  "isActive": false,
  "createdAt": "2024-08-02T20:55:31.505Z",
  "updatedAt": "2024-08-02T20:55:31.505Z"
}

## HTTP CODE - 400 ##

HTTP/1.1 400 Bad Request
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 118
ETag: W/"76-Swux8PAniNuiH0Lztp4MOhSnM/8"
Date: Sat, 03 Aug 2024 15:54:11 GMT
Connection: close

{
  "statusCode": 400,
  "timestamp": "2024-08-03T15:54:11.660Z",
  "path": "/auth/application",
  "message": "Bad Request Exception"
}

## HTTP CODE - 409 ##

HTTP/1.1 409 Conflict
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 143
ETag: W/"8f-1k5v7cga8C6UHCo9JuHtv/t1eWw"
Date: Sat, 03 Aug 2024 15:53:19 GMT
Connection: close

{
  "statusCode": 409,
  "timestamp": "2024-08-03T15:53:19.532Z",
  "path": "/auth/application",
  "message": "Application with slug first-app already exists"
}

HTTP/1.1 409 Conflict
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 148
ETag: W/"94-Hy6CdrDWjEJSr1rgjXNTxW7VuH0"
Date: Sat, 03 Aug 2024 15:53:54 GMT
Connection: close

{
  "statusCode": 409,
  "timestamp": "2024-08-03T15:53:54.374Z",
  "path": "/auth/application",
  "message": "Application with IP ::ffff:127.0.0.1 already exists"
}