### Request ###

PUT /auth/application/89b4df19-bd80-498b-bb95-186efb85829e HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "appSlug": "new-app",
  "isActive": false
}

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 190
ETag: W/"be-lrKHoatHmdi//odkIx/yOK4kF80"
Date: Fri, 02 Aug 2024 21:07:08 GMT
Connection: close

{
  "id": "89b4df19-bd80-498b-bb95-186efb85829e",
  "appSlug": "new-app",
  "appIp": "::ffff:127.0.0.1",
  "isActive": false,
  "createdAt": "2024-08-02T20:55:31.505Z",
  "updatedAt": "2024-08-02T21:07:08.416Z"
}

## HTTP CODE - 400 ##

HTTP/1.1 400 Bad Request
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 155
ETag: W/"9b-L2VxRwf+wLmjBsy8zc5Fa31/JCU"
Date: Sat, 03 Aug 2024 15:54:43 GMT
Connection: close

{
  "statusCode": 400,
  "timestamp": "2024-08-03T15:54:43.450Z",
  "path": "/auth/application/89b4df19-bd80-498b-bb95-186efb85829e",
  "message": "Bad Request Exception"
}

## HTTP CODE - 404 ##

HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 200
ETag: W/"c8-qrWUzYI1sWP6ZzmqdYu0+6Ylgdg"
Date: Sat, 03 Aug 2024 15:49:16 GMT
Connection: close

{
  "statusCode": 404,
  "timestamp": "2024-08-03T15:49:16.358Z",
  "path": "/auth/application/89b4df19-bd80-498b-bb95-186efb85829e",
  "message": "Application with ID 89b4df19-bd80-498b-bb95-186efb85829e not found"
}